### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by MitchellBouwman** [taskforcedev/faq#1]
After a `composer update`:

>   Problem 1
>     - The requested package taskforcedev/faq could not be found in any version,                                 there may be a typo in the package name.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your min                                imum-stability setting
>   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det                                ails.

**Comment by ghost** [comment]
Hi,  this is because the instructions I created say to pull v1.0 but I haven't pushed the tag for v1.0, I will do this now.

**Comment by ghost** [comment]
As a side note I did start refactoring to use the support package I created instead of having the config repeated for each package, so let me know if anything still does not work.  tag is pushed now.

**Comment by ghost** [comment]
Instructions for which are here: https://github.com/taskforcedev/laravel-support :)

**Comment by MitchellBouwman** [comment]
Running in the next problem after a:
`php artisan vendor:publish --provider="Taskforcedev\LaravelFaq\ServiceProvider" --tag="config"`

> Nothing to publish for tag [config].

**Comment by ghost** [comment]
Yes this is from the old documentation, instead please do `php artisan vendor:publish --tag="taskforce-support"` (after adding the laravel support service provider).

**Comment by ghost** [comment]
@MitchellBouwman just following up, did you get it working?

**Comment by MitchellBouwman** [comment]
@PrivateSniper Yes! Sorry I forgot. Great work!

**Comment by ghost** [comment]
No problem, will close the issue, thanks :)
